from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .enviosDetailView import EnviosDetailView
from .enviosListCreateView import EnviosListCreateView
from .trabajadoresDetailView import TrabajadoresDetailView
from .trabajadoresListCreateView import TrabajadoresListCreateView
from .transportadoresDetailView import TransportadoresDetailView
from .transportadoresListCreateView import TransportadoresListCreateView